name: Docker Image CI

on:
  push:
    branches: [ docker-building-image ]
  pull_request:
    branches: [ docker-building-image ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Inspect builder
      run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    - name: Buildx
      run: |
          docker build . # should run buildx

